FROM opennhp-base:latest AS building

COPY . /building
WORKDIR /building

RUN go mod tidy

RUN make frpc

FROM ubuntu:22.04 AS runtime

COPY --from=building /building/bin/ /qurl-proxy/

ENTRYPOINT ["/qurl-proxy/qurl-frpc", "-c", "/qurl-proxy/etc/frpc.toml"]